name: floward
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 

  cupertino_icons: ^1.0.2
  flutter_lints: ^1.0.0

  # Bottom Nav Bar Packages
  persistent_bottom_nav_bar: ^4.0.2
  
  # Getx Packages
  get: ^4.6.1

  # Localization Packages
  easy_localization: ^3.0.0
  
  # Icons Packages
  font_awesome_flutter: ^9.2.0 

  # Shared Preferences Packages
  shared_preferences: ^2.0.13
  get_storage: ^2.0.3

  # Network Packages
  dio: ^4.0.0
  dio_logger: ^4.0.8+8

  # Internet Packages
  internet_connection_checker: ^0.0.1+3

  # Images Packages
  image_picker: ^0.8.5+3
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0

  # Styling Packages
  flutter_staggered_animations: ^1.0.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_localizations:
    sdk: flutter 

flutter:

  uses-material-design: true
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 500      

  assets:
   - assets/fonts/
